# Generated by Django 5.0.4 on 2024-04-10 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrgName', models.CharField(blank=True, max_length=125)),
                ('ProjectName', models.CharField(blank=True, max_length=125)),
                ('ApplicationName', models.CharField(blank=True, max_length=125)),
                ('AssessmentFile', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['xlsx'])])),
            ],
        ),
    ]
