# Generated by Django 5.0.4 on 2024-04-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain', models.CharField(blank=True, max_length=150)),
                ('SubDomain', models.CharField(blank=True, max_length=150)),
                ('Question', models.CharField(max_length=500)),
                ('Description', models.CharField(blank=True, max_length=500)),
                ('Level', models.IntegerField(blank=True)),
                ('Weight', models.FloatField()),
                ('Remediation', models.CharField(blank=True, max_length=500)),
                ('Risk', models.CharField(blank=True, max_length=500)),
                ('Response', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial')], default='no', max_length=30)),
                ('Remarks', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
