# Generated by Django 5.0.4 on 2024-04-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentapp', '0002_assessmentquestionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentdetails',
            name='ApplicationName',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdetails',
            name='OrgName',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentdetails',
            name='ProjectName',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentquestionnaire',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentquestionnaire',
            name='Domain',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentquestionnaire',
            name='Level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentquestionnaire',
            name='Remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentquestionnaire',
            name='Remediation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentquestionnaire',
            name='Risk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentquestionnaire',
            name='SubDomain',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
