# Generated by Django 5.0.4 on 2024-04-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentapp', '0003_alter_assessmentdetails_applicationname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentquestionnaire',
            name='Response',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial')], default='no', max_length=30, null=True),
        ),
    ]
