# Generated by Django 5.0.4 on 2024-04-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentapp', '0004_alter_assessmentquestionnaire_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentquestionnaire',
            name='Level',
            field=models.IntegerField(default=1),
        ),
    ]
