# Generated by Django 5.0.4 on 2024-04-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentapp', '0005_alter_assessmentquestionnaire_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestionnaire',
            name='Rating',
            field=models.FloatField(default=0),
        ),
    ]
